version: '3.8'

services:
  bot:
    build: .
    container_name: anime_bot
    restart: always
    volumes:
      - ./database:/app/database
      - ./backups:/app/backups
    env_file:
      - .env
    ports:
      - "5000:5000"